[package]
edition = "2021"
name = "aoc2021"
version = "0.1.0"

[dependencies]
criterion = { version = "0.3.5", features = ["html_reports"] }

[[bench]]
harness = false
name = "bench"

[profile.release]
lto = true
