[package]
edition = "2021"
name = "aoc2021"
version = "0.1.0"

[dependencies]
criterion = { version = "0.3.5", features = ["html_reports"] }
paste = "1.0.6"
rayon = "1.5.1"

[[bench]]
harness = false
name = "bench"

[profile.release]
lto = true
